site_name: !ENV [SITE_NAME, 'my-juvix-project']
site_author: !ENV [SITE_AUTHOR, "Tara"]
site_description: !ENV [SITE_DESCRIPTION, "Documentation for my Juvix Application"]
site_url: !ENV [SITE_URL, 'https://juvix.org/docs']
site_dir: !ENV [SITE_DIR, 'docs']
copyright: !ENV [COPYRIGHT, "&copy; 2024 <a href=\"https://juvix.org\">Juvix</a>"]
use_directory_urls: false

nav:
  - Home: index.md
  - Test: test.juvix.md

plugins:
  - search
  - juvix

theme:
  name: !ENV [THEME, 'material']
  font:
    text: !ENV [FONT_TEXT, 'Inter']
    code: !ENV [FONT_CODE, 'Source Code Pro']



extra_css:
  - assets/css/source-nord.css
  - assets/css/source-macchiato.css
  - assets/css/juvix-highlighting.css
  - assets/css/juvix-material-style.css
  - assets/css/source-ayu-light.css
  - assets/css/linuwial.css

extra_javascript:
  - assets/js/mathjax.js
  - assets/js/toggle.js
  - assets/js/tex-svg.js
  - assets/js/highlight.js
